FROM archlinux:latest

# This file is meant for hosting relays

# Main port
EXPOSE 7777/tcp
EXPOSE 7777/udp

# Env vars
ENV DEBIAN_FRONTEND=noninteractive

# Dependencies
RUN pacman -Syu --noconfirm archlinux-keyring && \
    pacman -Syu --noconfirm \
        base-devel \
        sudo \
        git \
        sdl2 \
        glu \
        libglvnd \
        cmake \
        extra-cmake-modules \
        mingw-w64-binutils \
        mingw-w64-crt \
        mingw-w64-gcc \
        mingw-w64-headers \
        mingw-w64-winpthreads && \
    pacman -Scc --noconfirm

WORKDIR /build

COPY . .

RUN python3.12 -m venv .venv && \
    . .venv/bin/activate && \
    python3.12 -m pip install -r requirements.txt

CMD ["python3.12", "OutlastTogether.py", "--headless", "--config server_config.json"]
