FROM archlinux:latest

# This file is meant for hosting relays

# Main ports
EXPOSE 7777/tcp
EXPOSE 7777/udp

# Dependencies
RUN pacman -Syu --noconfirm archlinux-keyring && \
    pacman -Syu --noconfirm \
        base-devel \
        sudo \
        git \
        sdl2 \
        glu \
        libglvnd \
        cmake \
        extra-cmake-modules \
        mingw-w64-binutils \
        mingw-w64-crt \
        mingw-w64-gcc \
        mingw-w64-headers \
        mingw-w64-winpthreads && \
    pacman -Scc --noconfirm

# Copy the project
WORKDIR /opt/games/openol-relay
COPY . .

# Build
WORKDIR /opt/games/openol-relay/src

RUN cmake -S . -B build \
        -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build

# Start the relay
CMD ["./build/OpenOL_Relay"]
